version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-aluno
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aluno_online_backendp4
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      command: --default-authentication-plugin=mysql_native_password
        --init-file /docker-entrypoint-initdb.d/init.sql
      volumes:
        -- ./init.sql:/docker-entrypoint-initdb.d/init.sql


    ports:
      - "3307:3306"  # porta do host:porta do container
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  mysql_data:
